### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by Razew** [Razew/suvnet23-household-backsidegang#15]
Add visual aspects of login screen (not functionality)
Style:
- [x] Username TextInput
- [x] Password TextInput
- [x] Login button
- [x] Register button

Functionality:

Form validation
- [x] Check for empty fields
- [x] Check username constraints
- [x] Check password constraints
User credentials:
- [ ] Supabase auth?
Check if user is logged in at appstart (session)
- [ ] Supabase JWT/cookie?

**Comment by Razew** [comment]
Regarding this: 
>  Supabase auth?
Check if user is logged in at appstart (session)

The part about checking if already logged in at appstart, it will most likely be handled in the RootStackNavigator, so it should probably be an entirely separate issue. I believe I know how to handle that scenario.
