### ISSUE TITLE
Daily view

### ISSUE THREAD

**Issue by Razew** [Razew/suvnet23-household-backsidegang#47]
## Daily view
Found in `HouseholdScreen.tsx`

_(Issue format is WIP)_

### Display:

- [x] #48
- [x] All chores for 'today'
- [x] Avatar of users that have completed the chore 'today'
- [x] Days since chore was last completed, if not completed today
- [x] If overdue, visually represent this on the number of days since last completion

### Interactive elements:
- [x] #70
- [x] #120
  <details><summary>Details</summary>
  <p>
  Brings up an expanded view of the chore, with description, a checkbox or button for marking the chore as completed. If the user is an admin, there will be buttons for "Edit" and "Delete"-actions. At a later point in time, a picture and voice recording would be accessible in this expanded view.
  </p>
  </details>
